# Generated by Django 5.2.6 on 2025-10-18 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deezer_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen_url', models.URLField(blank=True, max_length=255, null=True)),
                ('fans_deezer', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(max_length=16, unique=True)),
                ('nombre', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deezer_id', models.CharField(blank=True, max_length=64, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('portada_url', models.URLField(blank=True, max_length=255, null=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='home.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deezer_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('duracion', models.IntegerField(blank=True, null=True)),
                ('preview_url', models.URLField(blank=True, max_length=255, null=True)),
                ('emotion_scores', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canciones', to='home.album')),
                ('artista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canciones', to='home.artista')),
                ('top_emocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canciones_top', to='home.emocion')),
            ],
        ),
        migrations.CreateModel(
            name='CancionEmocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('source', models.CharField(choices=[('goemotions', 'goemotions'), ('user', 'user')], default='goemotions', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emociones', to='home.cancion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='home.emocion')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='home.cancion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reproduccion', models.DateTimeField(auto_now_add=True)),
                ('segundos_escuchados', models.IntegerField(blank=True, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproducciones', to='home.cancion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('portada_url', models.URLField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('es_publica', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.cancion')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.playlist')),
            ],
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artista'], name='home_album_artista_73b2e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('titulo', 'artista')},
        ),
        migrations.AddIndex(
            model_name='cancionemocion',
            index=models.Index(fields=['emocion'], name='home_cancio_emocion_647035_idx'),
        ),
        migrations.AddIndex(
            model_name='cancionemocion',
            index=models.Index(fields=['cancion', 'emocion'], name='home_cancio_cancion_057585_idx'),
        ),
        migrations.AddIndex(
            model_name='cancionemocion',
            index=models.Index(fields=['source'], name='home_cancio_source_46bb7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cancionemocion',
            unique_together={('cancion', 'emocion', 'source')},
        ),
        migrations.AddIndex(
            model_name='cancion',
            index=models.Index(fields=['top_emocion'], name='home_cancio_top_emo_a06c98_idx'),
        ),
        migrations.AddIndex(
            model_name='cancion',
            index=models.Index(fields=['artista'], name='home_cancio_artista_ce59b9_idx'),
        ),
        migrations.AddIndex(
            model_name='cancion',
            index=models.Index(fields=['album'], name='home_cancio_album_i_a30c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='favorito',
            index=models.Index(fields=['usuario'], name='home_favori_usuario_aa8640_idx'),
        ),
        migrations.AddIndex(
            model_name='favorito',
            index=models.Index(fields=['cancion'], name='home_favori_cancion_3a6b1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'cancion')},
        ),
        migrations.AddIndex(
            model_name='historial',
            index=models.Index(fields=['usuario', 'fecha_reproduccion'], name='home_histor_usuario_497df6_idx'),
        ),
        migrations.AddIndex(
            model_name='historial',
            index=models.Index(fields=['cancion', 'fecha_reproduccion'], name='home_histor_cancion_02be95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('usuario', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='playlistcancion',
            index=models.Index(fields=['playlist'], name='home_playli_playlis_75a5c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistcancion',
            unique_together={('playlist', 'cancion')},
        ),
    ]
