# Generated by Django 5.2.6 on 2025-10-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_seed_emociones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='preview_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
