# Generated by Django 5.2.6 on 2025-11-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cancion_preview_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='portada_url',
        ),
        migrations.AddField(
            model_name='playlist',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
