# Generated by Django 5.2.6 on 2025-11-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_playlist_portada_url_playlist_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
