# Generated by Django 5.2.6 on 2025-11-08 06:12

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_playlist_fecha_actualizacion_and_more'),
    ]

    operations = []

    if settings.DATABASES['default']['ENGINE'].endswith('mysql'):
        operations = [
            migrations.RunSQL(
                sql="""
                    ALTER TABLE home_playlist
                    MODIFY COLUMN fecha_creacion DATETIME(6) NOT NULL
                    DEFAULT CURRENT_TIMESTAMP(6)
                    """,
                reverse_sql=migrations.RunSQL.noop
            ),
            migrations.RunSQL(
                sql="""
                    ALTER TABLE home_playlist
                    MODIFY COLUMN fecha_actualizacion DATETIME(6) NOT NULL
                    DEFAULT CURRENT_TIMESTAMP(6)
                    ON UPDATE CURRENT_TIMESTAMP(6)
                    """,
                reverse_sql=migrations.RunSQL.noop
            ),
        ]
